### ISSUE TITLE
Error when run

### ISSUE THREAD

**Issue by jacksonw765** [Julioocz/instagram-uploader#1]
I get this issue when I run with the default options. I have all the folders and documents created and in the proper position. What am I doing wrong?

Traceback (most recent call last):
  File "/usr/local/bin/instagram_uploader", line 9, in <module>
    load_entry_point('instagram-uploader==0.1', 'console_scripts', 'instagram_uploader')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/instagram_uploader.py", line 6, in <module>
    from InstagramAPI import InstagramAPI
  File "/home/jackson/src/instagramapi/InstagramAPI/__init__.py", line 1, in <module>
    from InstagramAPI.InstagramAPI import InstagramAPI
  File "/home/jackson/src/instagramapi/InstagramAPI/InstagramAPI.py", line 30, in <module>
    from moviepy.editor import VideoFileClip
  File "/usr/local/lib/python2.7/dist-packages/moviepy/editor.py", line 22, in <module>
    from .video.io.VideoFileClip import VideoFileClip
  File "/usr/local/lib/python2.7/dist-packages/moviepy/video/io/VideoFileClip.py", line 3, in <module>
    from moviepy.video.VideoClip import VideoClip
  File "/usr/local/lib/python2.7/dist-packages/moviepy/video/VideoClip.py", line 20, in <module>
    from .io.ffmpeg_writer import ffmpeg_write_image, ffmpeg_write_video
  File "/usr/local/lib/python2.7/dist-packages/moviepy/video/io/ffmpeg_writer.py", line 15, in <module>
    from moviepy.config import get_setting
  File "/usr/local/lib/python2.7/dist-packages/moviepy/config.py", line 38, in <module>
    FFMPEG_BINARY = get_exe()
  File "/usr/local/lib/python2.7/dist-packages/imageio/plugins/ffmpeg.py", line 86, in get_exe
    raise NeedDownloadError('Need ffmpeg exe. '
imageio.core.fetching.NeedDownloadError: Need ffmpeg exe. You can download it by calling:
  imageio.plugins.ffmpeg.download()

**Comment by edsoncudjoe** [comment]
Hi it looks like it can't find ffmpeg on your system. Do you have it installed?
